# Generated by Django 4.0.10 on 2023-12-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=50)),
                ('art', models.FileField(upload_to='uploads')),
                ('info', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
