# Generated by Django 4.0.10 on 2024-01-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('introdcution', models.TextField()),
                ('location', models.TextField()),
                ('services', models.TextField()),
            ],
        ),
    ]
